In [2]:
import pandas as pd
import numpy as np
import missingno as msno

In [3]:
df= pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/TheTitanic.csv', na_values=['**','?'], skiprows=1)

In [4]:
df

,sn,pclass,survived,Unnamed: 3,gender,age,family,fare,embarked,date
0,1,3,0,Mr. Anthony,male,42.0,0.0,7.5500,NaN,01-Jan-90
1,1,3,0,Mr. Anthony,male,42.0,0.0,7.5500,NaN,01-Jan-90
2,2,3,0,Master. Eugene Joseph,male,NaN,2.0,20.2500,S,02-Jan-90
3,3,2,0,"Abbott, Mr. Rossmore Edward",NaN,NaN,2.0,NaN,S,03-Jan-90
4,4,3,1,"Abbott, Mr. Rossmore Edward",female,35.0,2.0,20.2500,S,04-Jan-90
...,...,...,...,...,...,...,...,...,...,...
1296,1296,2,0,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24.0,0.0,13.0000,S,19-Jul-93
1297,1297,3,0,"Zabour, Miss. Hileni",female,14.5,1.0,14.4542,C,20-Jul-93
1298,1298,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0.0,7.2250,C,21-Jul-93
1299,1299,3,0,"Zakarian, Mr. Ortin",male,27.0,0.0,7.2250,C,22-Jul-93
1300,1300,3,0,"Zimmerman, Mr. Leo",male,29.0,0.0,7.8750,S,23-Jul-93

In [5]:
df.isna().sum()

sn              0
pclass          0
survived        0
Unnamed: 3      0
gender          1
age           258
family          2
fare            3
embarked        6
date            0
dtype: int64

**Lets Use Drop Function**

In [6]:
df.dropna()

,sn,pclass,survived,Unnamed: 3,gender,age,family,fare,embarked,date
4,4,3,1,"Abbott, Mr. Rossmore Edward",female,35.0,2.0,20.2500,S,04-Jan-90
5,5,3,1,"Abelseth, Miss. Karen Marie",female,16.0,0.0,7.6500,S,05-Jan-90
6,6,3,1,"Abelseth, Mr. Olaus Jorgensen",male,25.0,0.0,7.6500,S,06-Jan-90
7,7,2,0,"Abelson, Mr. Samuel",male,30.0,1.0,24.0000,C,07-Jan-90
8,8,2,1,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1.0,24.0000,C,08-Jan-90
...,...,...,...,...,...,...,...,...,...,...
1296,1296,2,0,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24.0,0.0,13.0000,S,19-Jul-93
1297,1297,3,0,"Zabour, Miss. Hileni",female,14.5,1.0,14.4542,C,20-Jul-93
1298,1298,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0.0,7.2250,C,21-Jul-93
1299,1299,3,0,"Zakarian, Mr. Ortin",male,27.0,0.0,7.2250,C,22-Jul-93
1300,1300,3,0,"Zimmerman, Mr. Leo",male,29.0,0.0,7.8750,S,23-Jul-93

**Fill na**

In [7]:
df['age'].mean()

29.978830297219556

In [8]:
df['age'].fillna(df['age'].mean())

0       42.00000
1       42.00000
2       29.97883
3       29.97883
4       35.00000
          ...
1296    24.00000
1297    14.50000
1298    26.50000
1299    27.00000
1300    29.00000
Name: age, Length: 1301, dtype: float64

In [9]:
df['fare'].median()

14.4542

In [10]:
df['fare'].fillna(14.45)

0        7.5500
1        7.5500
2       20.2500
3       14.4500
4       20.2500
         ...
1296    13.0000
1297    14.4542
1298     7.2250
1299     7.2250
1300     7.8750
Name: fare, Length: 1301, dtype: float64

In [11]:
df['gender']

0         male
1         male
2         male
3          NaN
4       female
         ...
1296    female
1297    female
1298      male
1299      male
1300      male
Name: gender, Length: 1301, dtype: object

In [12]:
df['gender'].bfill()

0         male
1         male
2         male
3       female
4       female
         ...
1296    female
1297    female
1298      male
1299      male
1300      male
Name: gender, Length: 1301, dtype: object

In [13]:
df['age']

0       42.0
1       42.0
2        NaN
3        NaN
4       35.0
        ...
1296    24.0
1297    14.5
1298    26.5
1299    27.0
1300    29.0
Name: age, Length: 1301, dtype: float64

In [14]:
df['age'].interpolate()

0       42.000000
1       42.000000
2       39.666667
3       37.333333
4       35.000000
          ...
1296    24.000000
1297    14.500000
1298    26.500000
1299    27.000000
1300    29.000000
Name: age, Length: 1301, dtype: float64

**Now using Sklearn Algorithms**

In [25]:
from sklearn.impute import SimpleImputer
si= SimpleImputer(strategy= 'constant', fill_value=0)

In [27]:
df[['age', 'fare']]= si.fit_transform(df[['age', 'fare']])

**We need to overwrite**

In [29]:
df[['age', 'fare']]

       age     fare
0     42.0   7.5500
1     42.0   7.5500
2      0.0  20.2500
3      0.0   0.0000
4     35.0  20.2500
...    ...      ...
1296  24.0  13.0000
1297  14.5  14.4542
1298  26.5   7.2250
1299  27.0   7.2250
1300  29.0   7.8750

[1301 rows x 2 columns]

**KNN Imputer**

In [34]:
from sklearn.impute import KNNImputer
knni= KNNImputer()

In [32]:
df[['family']]

      family
0        0.0
1        0.0
2        2.0
3        2.0
4        2.0
...      ...
1296     0.0
1297     1.0
1298     0.0
1299     0.0
1300     0.0

[1301 rows x 1 columns]

In [36]:
df[['family']]= knni.fit_transform(df[['family']])

In [37]:
df[['family']]

      family
0        0.0
1        0.0
2        2.0
3        2.0
4        2.0
...      ...
1296     0.0
1297     1.0
1298     0.0
1299     0.0
1300     0.0

[1301 rows x 1 columns]